version: '3.7'
name: servr

volumes:
  postgres-data:

services:
  postgres:
    container_name: servr_db
    image: postgres:14-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root